### ISSUE TITLE
Compilation issue in Windows

### ISSUE THREAD

**Issue by xtingray** [feeef/QTMyPaint#1]
Using Qt 5.5.0 from a Windows environment I got this compilation error message:

`
make[2]: Entering directory 'C:/devel/sources/QTMyPaint/json-c'
gcc -c -pipe -fno-keep-inline-dllexport -g -Wall -Wextra -DUNICODE -DQT_CORE_LIB -I. -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/include -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/include/QtCore -Idebug -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/mkspecs/win32-g++  -o debug/arraylist.o arraylist.c
gcc -c -pipe -fno-keep-inline-dllexport -g -Wall -Wextra -DUNICODE -DQT_CORE_LIB -I. -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/include -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/include/QtCore -Idebug -I../../../qt-5.5.0/qt-5.5.0-x64-mingw510r0-sjlj-rev0/mkspecs/win32-g++  -o debug/debug.o debug.c
debug.c:20:21: fatal error: syslog.h: No such file or directory
`

Any suggestion?

**Comment by xtingray** [comment]
To fix the problem, all I had to do was to edit the file QTMyPaint\json-c\debug.c and add the conditional Q_OS_UNIX around every syslog definition/call, like this:

```
#ifdef Q_OS_UNIX
#if HAVE_SYSLOG_H
# include <syslog.h>
#endif 
#endif
```

Now the compilation is clean and I could test the demo in Windows :)

**Comment by feeef** [comment]
Thanks a lot for your help @xtingray!

If you have forked this repo, can you send me a pull request? Otherwise I will fix it on my side.

**Comment by xtingray** [comment]
Give me a couple of days and I send you some basic enhancements related to warnings and compilation issues ;)

**Comment by feeef** [comment]
Great! Thanks you very much!

**Comment by feeef** [comment]
I have merged your pull request so I close this issue. Thanks again!

**Comment by feeef** [comment]
@xtingray , just to let you know, I have found the time to work on the lib this week end and completed most of the features I planed to implement on it. It is much more mature now. Just check the demo app.

**Comment by xtingray** [comment]
Sure! I will... thank you for this update, I'm really interested in your
project :)

2016-04-04 4:28 GMT-05:00 François Téchené notifications@github.com:

> @xtingray https://github.com/xtingray , just to let you know, I have
> found the time to work on the lib this week end and completed most of the
> features I planed to implement on it. It is much more mature now. Just
> check the demo app.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/feeef/QTMyPaint/issues/1#issuecomment-205210996

## 

# 

  Gustav Gonzalez

#   xtingray@gmail.com
