### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by xtingray** [feeef/QTMyPaint#4]
I was looking inside the QTMyPaint.pro file and I noticed that you are listing headers and sources of the demo app directly from there. This is not a good practice. As I remember, initially every subdirectory contained its own .pro file and every component was compiled generating its own object files inside, now I see moc_*.o files in the project root (not so elegant, in fact, ugly).

My advice: Get back the .pro file as you had it at the beginning. The compilation of the demo source code must occur inside the demo directory, and the executable has to be created inside that location.

Think of this project as a set of modules, where every module must be independent "as possible". Obviously, you must to call dependencies between them, but do it as in the first version of the code. Of course, the last module to compile should be the demo app, after the dependencies.

Understanding that QTMyPaint is not an app, but some kind of library/dependency for other projects, order and a clean design  matters. 

If you have any doubt, please, let me know and keep up the hard work! :)

**Comment by feeef** [comment]
Thanks for the feedback! 

With the previous configuration, it was working without including json-c within libmypaint. As soon as I have been in need of json-c I couldn't build anymore, it was saying that it couldn't link to the required json files. After spending an hour trying to debug the .pro files, checking all the include and depends paths, I ended up having all my files in the same project. I just wanted it to build for me to go forward.

I am aware that the way of organizing the project is not right and it is just a matter of modifying the .pro file.

I could just have 2 projects. One for the demo and on for the libs all together...?

I am not an expert with QT so if you know how to setup the pro files the right way, please do!

Cheers!

**Comment by xtingray** [comment]
Please, check the pull request that I sent you. I compiled this source code and tested the demo binary in Windows, Mac and Linux with no issues.

To compile it from Linux, just run from any console:
cd QTMyPaint
qmake
make
./demo/demo
Note: For Windows and Mac, same instructions but the path of the demo binary changes.

About your question: there is no need of splitting the project to keep working on the demo part, it is just an example of how to use the library, so it should be included as part of the main package.

This project is going great! I definitely will include it as a dependency of Tupi :)

PS:  Is there any chance to use lowercase letters for the project name? QTMyPaint -> qtmypaint or qt-mypaint. Usually on Unix, that's the standard (just a suggestion).

**Comment by feeef** [comment]
It is working perfectly! Thanks a lot @xtingray !

I agree with the naming convention as well. I will change it to qtmypaint.

Are you maintainer of Tupi? I am myself a maintainer of Pencil2D. Anyway, feel free to add the lib in Tupi! I am happy to help more great free and open source animation software to improve! :)
