### ISSUE TITLE
Use a less restrictive license

### ISSUE THREAD

**Issue by feeef** [feeef/QTMyPaint#8]
I choose the GPLv3 license as a wish to support the copyleft philosophy. I realize that this license is restricting the use of this lib in many free software projects so I plan to change it to a less restrictive one.

**Comment by feeef** [comment]
I plan to use the Modified BSD License : http://directory.fsf.org/wiki/License:BSD_3Clause

Or the X11 License : http://directory.fsf.org/wiki/License:X11

Which are both compatible with the GPLv2 and GPLv3 licenses.

**Comment by ghost** [comment]
Thank you so much for considering this change.  It will make incorporating libmypaint into OpenToonz much easier.  OpenToonz uses BSD, so that would be my preference, but I'm just excited to be able to use it.

**Comment by feeef** [comment]
Thank you @turtletooth !
Other persons suggested the Modified BSD License, it is very common and approved by the FSF for this kind of project so I will go for the one.

**Comment by feeef** [comment]
I have made the change so feel free to fork and use this project as you wish! :)

**Comment by blurymind** [comment]
THANK YOU !! :D
